//------------------------------------------------------------------------------
// <auto-generated>
// This code was created by the program tool.
// Runtime environment version: 4.0.30319.42000
//
// Changes to this file may cause incorrect behavior and will be lost if the
// the code is re-created.
// </auto-generated>
//------------------------------------------------------------------------------

namespace defi.Properties
{


    /// Resource class with strict type for searching localized strings, etc.
    /// </summary>
    // This class was automatically created using StronglyTypedResourceBuilder
    // class using tools such as ResGen or Visual Studio.
    // To add or remove a member, modify the .ResX file and then restart ResGen
    // with the /str parameter or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        /// Return the cached instance of the ResourceManager used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("defi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the CurrentUICulture property of the current thread for all
        /// resource substitutions using this strict type resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
